# Generated by Django 3.2.7 on 2021-09-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('plates', models.CharField(max_length=100)),
                ('stops', models.CharField(max_length=100)),
                ('wheels', models.CharField(max_length=100)),
                ('bearings', models.CharField(max_length=100)),
                ('cushions', models.CharField(max_length=100)),
                ('slides', models.CharField(max_length=100)),
            ],
        ),
    ]
