# Generated by Django 3.2.7 on 2021-09-15 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('equipment', models.CharField(choices=[('B', 'Bearings'), ('T', 'Toe stops'), ('P', 'Plates'), ('W', 'Wheels'), ('S', 'Slider blocks'), ('C', 'Cushions'), ('O', 'Other')], default='B', max_length=1)),
                ('entry', models.CharField(max_length=250)),
                ('skate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.skate')),
            ],
        ),
    ]
