# Generated by Django 3.2.7 on 2021-09-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='maintenance date'),
        ),
    ]
